### ISSUE TITLE
Holo lighting without duration doesn't work

### ISSUE THREAD

**Issue by ethax-ross** [reeltwo/Reeltwo#10]
I installed the AstroPixelPlus firmware today using the latest version of ReelTwo; everything seems to work great apart from the holo projector light sequences. I get the random lighting but when I issue a command from the R2Touch app it just cancels any ongoing animation and nothing else happens.

I dug into it a little and I can get it working if I pass a duration to the command, so this will work but without the `|10` nothing happens:

```
HPF0040|10
```

Oddly, when I try the original command sequence (without duration) in the ReelTwo simulator it works great and appears to run indefinitely/until its interrupted which is what I would expect. However, when I download ReelTwo and modify the Astropixels example sketch I have the same issue as with the AstropPixelPlus firmware; it doesn't light at all without an explicit duration in the command.

I started trying to debug this in ReelTwo but I can't figure out how to modify the library when in an example Sketch and have it recompile, so I've not got very far...

**Comment by rimim** [comment]
Thanks for reporting the issue. I actually ran into this issue too when making the video. I'll get the fix checked in later today.

**Comment by ethax-ross** [comment]
Ah amazing, thanks @rimim!
